import { setPersistedColorScheme } from "../lib/colorScheme";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={`bg-neutral-50 dark:bg-neutral-900 ${inter.className}`}>
        <script
          dangerouslySetInnerHTML={{
            __html: `(${setPersistedColorScheme.toString()})()`,
          }}
        />

        <div className="mx-auto max-w-6xl">{children}</div>
      </body>
    </html>
  );
}
