import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-neutral-50 dark:bg-neutral-900 h-full">
      <body className={`h-full ${inter.className}`}>
        <div
          className="max-w-6xl mx-auto h-full grid gap-8"
          style={{ gridTemplateRows: "auto minmax(0, 1fr)" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
